---
title: "Nosautoanalizamos"
author: "Lucía Martínez Valderas"
date: "2024-05-03"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

## Importacion
```{r}
library(readr)
arch <- read.csv("./data/NosAutoanalizamos2024 - Hoja1.tsv",skip=25, sep="\t")
#Elimino las ultimas lineas ya que son erroneas
arch <- arch[arch$Id != "",]
arch
```
```{r}
#Función para averiguar la codificacion del archivo 
codificacion<-guess_encoding("data/NosAutoanalizamos2024 - Hoja1.tsv")
#unique nos da los valores unicos de una conjunto
sex<-unique(arch$Sex)
#Cambiamos el tipo de datos necesarios 
VarFactor<-c("Id","Sex","NW.Hnd","Fold","Clap","Smoke")
VarNum<-c("Age","Wr.Hnd","Pulse","Exer","Height","ALG","ANM","FP","DCS","MD","HSt","Hwork")
VarFecha<-("FechaNac(DD-MM-YYY)")

#Cambiar varibales numéricas
for(i in VarNum){
  arch[[i]]<-as.numeric(arch[[i]])
}
#Cambiar las varibales factor
for(i in VarFactor){
  arch[[i]]<-as.factor(arch[[i]])
}
#Cambiar la fecha
arch$FechaNac.DD.MM.YYY.<-as.Date(arch$FechaNac.DD.MM.YYY., format="%d-%m-%Y")
arch

```
```{r}
library(dplyr)
#sapply aplica una función sobre las columnas
sapply(arch[, VarFactor], unique)
sapply(arch[, VarNum], unique)
#Correguir los errores por ejemplo si, no, No
fold<-c("Izquierdo", "Derecho", "Izquierda", "derecha","Derecha") 
arch$Fold %>% recode("Izquierdo"="Izquierda","Derecho"="Derecha","derecha"="Derecha","Derecha"="Derecha","Izquierda"="Izquierda")
arch
```













